force-app/main/default/objects/Picklist_Updater__c/Picklist_Updater__c.object-meta.xml
<CustomObject>
    <label>Picklist Updater</label>
    <nameField>
        <displayFormat>PU-{0000}</displayFormat>
        <label>Picklist Updater Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklist Updaters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist_Updater__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Types of Action you want to perform.</description>
    <inlineHelpText>Select the Types of Action you want to perform.</inlineHelpText>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Add Single Value</fullName>
            </value>
            <value>
                <fullName>Add Primary &amp; Dependent Field Values</fullName>
            </value>
            <value>
                <fullName>Deactivate Value</fullName>
            </value>
            <value>
                <fullName>Update Dependency Only (existing values)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Picklist_Updater__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <inlineHelpText>Select the object name</inlineHelpText>
    <label>Object Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Main__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Picklist_Updater__c/fields/Secondary_Values__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Values__c</fullName>
    <inlineHelpText>Add values for secondary picklist</inlineHelpText>
    <label>Dependent Field Values</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MyRecordController.cls
public with sharing class MyRecordController {
    @AuraEnabled(cacheable=true)
    public static List<Picklist_Updater__c> getRecords(Id recordId) {
        // Query to fetch records based on the recordId
        // Replace MyObject__c with your actual object name and include necessary fields
        return [SELECT Action__c, Object_Name__c, Secondary_Values__c FROM Picklist_Updater__c WHERE Id = :recordId];
    }
}